name: Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Choose a branch
        required: true
        default: main
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  BRANCH: ${{ github.event.inputs.branch }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}

      - name: Install dependencies
        run: npm install

      - name: test branch     
        if: ${{ env.BRANCH == 'main' }}
        run: |
          echo "Main branch" 
