name: Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Choose a branch
        required: true
        default: main
  push:
    branches:
      - ${{ workflow_dispatch.inputs.branch }}
    tags-ignore:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
